name: Bump Cask

on:
  - workflow_dispatch

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew cask
        uses: Homebrew/actions/bump-packages@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1
        with:
          token: ${{secrets.TOKEN}}
          casks: >
            vrcx-team/homebrew-vrcx-tap/vrcx
            vrcx-team/homebrew-vrcx-tap/vrcx@nightly
          fork: false

  automerge:
    runs-on: ubuntu-latest
    needs: [bump-casks]
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.TOKEN }}
          merge-method: rebase
          pull-request-author-associations: MEMBER,OWNER
          dry-run: false
